# Generated by Django 4.1.4 on 2023-02-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationName', models.CharField(max_length=15)),
                ('destinationDescription', models.TextField(max_length=100)),
                ('destinationPrize', models.IntegerField()),
                ('destinationImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
