# Generated by Django 4.1.4 on 2023-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='destinationImage',
            field=models.ImageField(default='null.jpg', upload_to='img'),
        ),
    ]
