# Generated by Django 4.1.4 on 2023-02-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_destinations_destinationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.IntegerField(max_length=15)),
            ],
        ),
    ]
